about/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path("", index),
]

blog/urls.py
from django.urls import path
from .views import index, article, detail

urlpatterns = [
    path('', index, name="index"),
    path("blog/detail/<int:pk>/", detail, name="blog_detail"),
    path('article/', article, name="article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact

urlpatterns = [
    path('', contact)
]

about/models.py
from django.db import models


class Team(models.Model):
    mission = models.CharField(max_length=202)
    vision = models.CharField(max_length=202)
    value = models.CharField(max_length=202)
    video = models.FileField(upload_to="team_videos/")

    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mission


class Clients(models.Model):
    text = models.CharField(max_length=202)
    image = models.ImageField(upload_to="clients/")
    full_name = models.CharField(max_length=20)
    job = models.CharField(max_length=20)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

blog/models.py
from tkinter.constants import CASCADE

from django.db import models


class Blog(models.Model):
    name = models.CharField(max_length=15)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="blog_images/")
    twitter = models.CharField(max_length=50)
    facebook = models.CharField(max_length=50)
    instagram = models.CharField(max_length=50)

    create_at = models.DateTimeField(auto_now_add=True)
    read_minute = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="article_images/")
    day = models.CharField(max_length=2)
    year = models.CharField(max_length=4)
    month = models.CharField(max_length=15)
    info = models.CharField(max_length=100)

    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title



class Blog_info(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_infos")  # Added ForeignKey
    image = models.ImageField(upload_to="blog_single_photos/")
    title = models.CharField(max_length=50)
    text = models.TextField()

    second_title = models.CharField(max_length=50)
    second_image = models.ImageField(upload_to="second_blog_single_photos/")
    second_text = models.TextField()

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title




class Tags(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Author(models.Model):
    image = models.ImageField(upload_to="author_images/")
    full_name = models.CharField(max_length=20)
    info = models.CharField(max_length=202)

    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name



class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    full_name = models.CharField(max_length=202)
    message = models.TextField()
    telephone = models.CharField(max_length=20)


    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.full_name


class Categories(models.Model):
    cat = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="category")
    name = models.CharField(max_length=20)

contact/models.py
from django.db import models


class Contact(models.Model):
    full_name = models.CharField(max_length=202)
    email = models.EmailField()
    phone = models.CharField(max_length=202)
    message = models.TextField()
    is_published = models.BooleanField(default=False)

    create_at = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("id", "blog", "full_name", "message")
        exclude = ["blog"]

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

about/views.py
from django.shortcuts import render
from .models import Team, Clients


def index(request):
    my_team = Team.objects.all()
    client = Clients.objects.all()
    context = {
        "my_team": my_team,
        "client": client
    }
    return render(request, "about.html", context)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Article, Author, Blog_info, Comment
from .forms import CommentForm
from django.core.paginator import Paginator

def index(request):
    blog_list = Blog.objects.all().order_by('-create_at')  # Order blogs by latest
    paginator = Paginator(blog_list, 5)  # Show 5 posts per page

    page_number = request.GET.get('page')  # Get the page number from URL
    page_obj = paginator.get_page(page_number)  # Get the correct page

    context = {
        "page_obj": page_obj,  # Pass paginated blog list
    }
    return render(request, "index.html", context)

def detail(request, pk):
    blog = get_object_or_404(Blog, id=pk)  # Fetch blog or return 404
    blog_info = blog.blog_infos.all()  # Use related_name to get related blog info
    author = Author.objects.all()  # Only related author
    comments = blog.comments.all()  # Fetch related comments

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            com = comment_form.save(commit=False)
            com.blog = blog  # Associate comment with blog
            com.save()
            return redirect("detail", pk=pk)  # Redirect to the same detail page to clear form
    else:
        comment_form = CommentForm()  # Empty form on GET request

    context = {
        "blog": blog,
        "blog_info": blog_info,
        "author": author,
        "comment_form": comment_form,
        "comments": comments
    }

    return render(request, "blog-single.html", context)


def article(request):
    article_list = Article.objects.all().order_by('-create_at')  # Order articles by latest
    paginator = Paginator(article_list, 5)  # Show 5 articles per page

    page_number = request.GET.get('page')  # Get the page number from URL
    page_obj = paginator.get_page(page_number)  # Get the correct page

    context = {
        "page_obj": page_obj,  # Pass paginated articles
    }

    return render(request, "blog.html", context)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm



def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(".")

    context ={
        'form': form
    }

    return render(request, 'contact.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
        {% for i in my_team %}
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end"
                     style="background-image:url({% static 'images/about.jpg' %});">
                    <a href="https://www.youtube.com/watch?v=3xaVX0cluDo"
                       class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
            </div>
            <div class="col-md-6 pl-md-5 py-md-5">
                <div class="row justify-content-start pt-3 pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <span class="subheading">Welcome to Readit</span>
                        <h2 class="mb-4">We give you the best articles you want.</h2>
                        <p>Far, far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <div class="tabulation-2 mt-4">
                            <ul class="nav nav-pills nav-fill d-md-flex d-block">
                                <li class="nav-item mb-md-0 mb-2">
                                    <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
                                </li>
                                <li class="nav-item px-lg-2 mb-md-0 mb-2">
                                    <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
                                </li>
                            </ul>
                            <div class="tab-content bg-light rounded mt-2">
                                <div class="tab-pane container p-0 active" id="home1">
                                    <p>{{ i.mission }}</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home2">
                                    <p>{{ i.vision }}</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home3">
                                    <p>{{ i.value }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>


<!--Happy Clients-->
<section class="ftco-section testimony-section">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
                <span class="subheading">Testimonial</span>
                <h2 class="mb-4">Happy Clients</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel ftco-owl">
                    {% for i in client %}
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">{{ i.text }}</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({{ i.image.url }})"></div>
                                    <div class="pl-3">
                                        <p class="name">{{ i.full_name }}</p>
                                        <span class="position">{{ i.job }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <title>Readit - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index-2.html">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="/article/" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="/about/" class="nav-link">Team</a></li>
                <li class="nav-item"><a href="/contact/" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}


{% endblock %}

<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">

<!--            Read it-->
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="logo"><a href="#">Read<span>it</span>.</a></h2>
                    <p>Far, far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="https://x.com/ismatov_amirbek"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.facebook.com/"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/ismatov_amirbek_/"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>

<!--            latest News-->
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">latest News</h2>
                    <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"></span> Oct. 16, 2019</a></div>
                                <div><a href="#"></span> Admin</a></div>
                                <div><a href="#"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="/blog/"></span> Oct. 16, 2019</a></div>
                                <div><a href="#"></span> Admin</a></div>
                                <div><a href="#"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<!--            Information-->
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="/" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a>
                        </li>
                        <li><a href="/about/" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>About</a>
                        </li>
                        <li><a href="/article/" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
                        <li><a href="/contact/" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Contact</a>
                        </li>
                    </ul>
                </div>
            </div>

<!--            Have a Questions?-->
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="234a4d454c635a4c5651474c4e424a4d0d404c4e">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>

    </div>
</footer>


<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vef91dfe02fce4ee0ad053f6de4f175db1715022073587"
        integrity="sha512-sDIX0kl85v1Cl5tu4WGLZCpH/dV9OHbA4YlKCuCiMmOQIk4buzoYDZSFj+TvC71mOBLh8CDC/REgE0GX0xcbjA=="
        data-cf-beacon='{"rayId":"88c172532da42e15","b":1,"version":"2024.4.1","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/readit/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 May 2024 20:24:54 GMT -->
</html>

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Blog Single</h1>
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="/">Home <i class="ion-ios-arrow-forward"></i></a></span>
                    <span class="mr-2"><a href="{% url 'article' %}">Blog <i class="ion-ios-arrow-forward"></i></a></span>
                    <span>Blog Single <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="img-fluid">
                </p>
                <h2 class="mb-3">{{ blog.title }}</h2>
                <p>{{ blog.content }}</p>

                <!-- Blog Information -->
                {% for info in blog_info %}
                    <h2 class="mb-3">{{ info.title }}</h2>
                    <p>{{ info.text }}</p>
                    <p class="mb-5">
                        <img src="{{ info.image.url }}" alt="{{ info.title }}" class="img-fluid">
                    </p>
                {% endfor %}

                <!-- Tags -->
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        <a href="#" class="tag-cloud-link">Life</a>
                        <a href="#" class="tag-cloud-link">Sport</a>
                        <a href="#" class="tag-cloud-link">Tech</a>
                        <a href="#" class="tag-cloud-link">Travel</a>
                    </div>
                </div>

                <!-- Author -->
                {% for author in author %}
                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{{ author.image.url }}" alt="Author Image" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{ author.full_name }}</h3>
                        <p>{{ author.info }}</p>
                    </div>
                </div>
                {% endfor %}

                <!-- Comments Section -->
                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ blog.comments.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in blog.comments.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'images/person_1.jpg' %}" alt="User">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.full_name }}</h3>
                                <div class="meta mb-3">{{ comment.create_at }}</div>
                                <p>{{ comment.message }}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <!-- Leave a Comment Form -->
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a Comment</h3>
                        <form method="post" action="{% url 'detail' blog.id %}" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_full_name">Full Name *</label>
                                {{ comment_form.full_name }}
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email *</label>
                                {{ comment_form.email }}
                            </div>
                            <div class="form-group">
                                <label for="id_message">Message</label>
                                {{ comment_form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                <!-- Search -->
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>

                <!-- Categories -->
                <div class="sidebar-box ftco-animate">
                    <h3>Categories</h3>
                    <ul class="categories">
                        <li><a href="#">Illustration <span class="ion-ios-arrow-forward"></span></a></li>
                        <li><a href="#">Branding <span class="ion-ios-arrow-forward"></span></a></li>
                        <li><a href="#">Application <span class="ion-ios-arrow-forward"></span></a></li>
                        <li><a href="#">Design <span class="ion-ios-arrow-forward"></span></a></li>
                        <li><a href="#">Marketing <span class="ion-ios-arrow-forward"></span></a></li>
                    </ul>
                </div>

                <!-- Recent Blogs -->
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blogs</h3>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Tag Cloud -->
                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        <a href="#" class="tag-cloud-link">cat</a>
                        <a href="#" class="tag-cloud-link">abstract</a>
                        <a href="#" class="tag-cloud-link">people</a>
                        <a href="#" class="tag-cloud-link">person</a>
                        <a href="#" class="tag-cloud-link">model</a>
                        <a href="#" class="tag-cloud-link">delicious</a>
                        <a href="#" class="tag-cloud-link">desserts</a>
                        <a href="#" class="tag-cloud-link">drinks</a>
                    </div>
                </div>

                <!-- Paragraph -->
                <div class="sidebar-box ftco-animate">
                    <h3>About Blog</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique.</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}